name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: fortress
          POSTGRES_USER: fortress_user
          POSTGRES_PASSWORD: example
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend deps
        run: |
          cd Backend
          npm ci
      - name: Generate prisma client
        run: |
          cd Backend
          npx prisma generate
      - name: Typecheck
        run: |
          cd Backend
          npx tsc --noEmit
